### ISSUE TITLE
fix `validate` in sidekick: 

### ISSUE THREAD

**Issue by russHyde** [russHyde/data_buddy#41]
```
touch abc.yaml

./sidekick validate --yaml abc.yaml

Traceback (most recent call last):
  File "./sidekick", line 98, in <module>
    main()
  File "./sidekick", line 92, in main
    args.func(args)
  File "./sidekick", line 43, in validate
    subprocess.call(["python", validation_script, args.yaml])
  File "/home/ah327h/tools/miniconda3/envs/temp/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/ah327h/tools/miniconda3/envs/temp/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/home/ah327h/tools/miniconda3/envs/temp/lib/python3.6/subprocess.py", line 1275, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: expected str, bytes or os.PathLike object, not list

```

**Comment by russHyde** [comment]
Turns out this was due to `args.yaml` being a list but the code treating it as a string. So, calling 
```
subprocess.run(["python", some_script, args.yaml])
```
was invalid. Code should be replaced with

```
subprocess.run(["python", some_script] + args.yaml) 
# or
subprocess.run(["python", some_script, args.yaml[0]])
```
