### ISSUE TITLE
md5sum Validator should check if input_file exists

### ISSUE THREAD

**Issue by russHyde** [russHyde/data_buddy#45]
If a validation-tests.yaml file mentions an input-file that doesn't exist, the md5sum-based validation pipeline fails with the following error:

```
(nil_cpi_rita_rnaseq) ah327h@15:43:12:~/jobs_llr/nil_cpi_rita_rnaseq$ ./sidekick validate --yaml results_validation_tests.yaml 

Traceback (most recent call last):
  File "bin/buddy/buddy/validate_file_contents.py", line 30, in <module>
    run_workflow(ARGS.validate_yaml[0])                                                                                           
  File "bin/buddy/buddy/validate_file_contents.py", line 13, in run_workflow
    report = workflow.format_failure_report()                                                                                     
  File "/home/ah327h/jobs_llr/nil_cpi_rita_rnaseq/bin/buddy/buddy/validation_workflow.py", line 54, in format_failure_report
    failures = self.get_failing_validators()                                                                                      
  File "/home/ah327h/jobs_llr/nil_cpi_rita_rnaseq/bin/buddy/buddy/validation_workflow.py", line 42, in get_failing_validators
    return {k: v for k, v in self.validators.items() if not v.is_valid()}                                                         
  File "/home/ah327h/jobs_llr/nil_cpi_rita_rnaseq/bin/buddy/buddy/validation_workflow.py", line 42, in <dictcomp>
    return {k: v for k, v in self.validators.items() if not v.is_valid()}                                                         
  File "/home/ah327h/jobs_llr/nil_cpi_rita_rnaseq/bin/buddy/buddy/validation_classes.py", line 14, in is_valid
    return get_md5sum(self.input_file) == self.expected_md5sum                                                                    
  File "/home/ah327h/jobs_llr/nil_cpi_rita_rnaseq/bin/buddy/buddy/validation_classes.py", line 26, in get_md5sum
    md5 = str(sh.md5sum(filepath)).strip().split()[0]                                                                             
  File "/home/ah327h/tools/miniconda3/envs/nil_cpi_rita_rnaseq/lib/python3.6/site-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)                                                                  
  File "/home/ah327h/tools/miniconda3/envs/nil_cpi_rita_rnaseq/lib/python3.6/site-packages/sh.py", line 774, in __init__
    self.wait()                                                                                                                   
  File "/home/ah327h/tools/miniconda3/envs/nil_cpi_rita_rnaseq/lib/python3.6/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)                                                                                      
  File "/home/ah327h/tools/miniconda3/envs/nil_cpi_rita_rnaseq/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc                                                                                                                     
sh.ErrorReturnCode_1:

  RAN: /usr/bin/md5sum results/notebook_pdf_output/nested_lrt/cpi_in_rita.nested_contrast_lrt_top_tags.tsv                        
   
  STDOUT:                                                                                                                         
            
   
  STDERR:                                                                                                                         
/usr/bin/md5sum: results/notebook_pdf_output/nested_lrt/cpi_in_rita.nested_contrast_lrt_top_tags.tsv: No such file or directory
```

**Comment by russHyde** [comment]
Since `buddy::Md5sumValidator` calls shell functions rather than python functions, it should check that a file is valid before passing that file to the shell.
