### ISSUE TITLE
unbound PKGNAME when not making R package

### ISSUE THREAD

**Issue by russHyde** [russHyde/data_buddy#73]
For example:

```
JOB: /home/ah327h/jobs_repos/genomic_refs
./scripts/setup.sh: Running the work-package setup-script.
./scripts/setup.sh: 'buddy' has already been installed
./scripts/helpers_for_setup/setup_libs.sh: line 119: PKGNAME: unbound variable
Traceback (most recent call last):
  File "./sidekick", line 117, in <module>
    main()
  File "./sidekick", line 111, in main
    args.func(args)
  File "./sidekick", line 29, in setup
    subprocess.run(["./scripts/setup.sh"], check=True)
  File "/home/ah327h/tools/miniconda3/envs/genomic_refs/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['./scripts/setup.sh']' returned non-zero exit status 1
```

**Comment by russHyde** [comment]
Only need to refer to `PKGNAME` when inside the block for building the R package for the current project
