### ISSUE TITLE
`validate_dir_existence` should autoexpand `~` as home dir

### ISSUE THREAD

**Issue by russHyde** [russHyde/data_buddy#76]
Calling `./sidekick setup` with the existing directory `~/snap` stated in `./.sidekick/setup/check_these_dirs.yaml` threw an error

```
./sidekick setup

JOB: /home/ah327h/temp/my_new_project
./scripts/setup.sh: Running the work-package setup-script.
./scripts/setup.sh: 'buddy' has already been installed
Traceback (most recent call last):
  File "./bin/buddy/buddy/validate_dir_existence.py", line 46, in <module>
    run_workflow(ARGS.required_dirs_yaml[0])
  File "./bin/buddy/buddy/validate_dir_existence.py", line 28, in run_workflow
    errno.ENOENT, os.strerror(errno.ENOENT), current_dir
FileNotFoundError: [Errno 2] No such file or directory: '~/snap'
Traceback (most recent call last):
  File "./sidekick", line 117, in <module>
    main()
  File "./sidekick", line 111, in main
    args.func(args)
  File "./sidekick", line 29, in setup
    subprocess.run(["./scripts/setup.sh"], check=True)
  File "/home/ah327h/tools/miniconda3/envs/temp/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['./scripts/setup.sh']' returned non-zero exit status 1.
```

**Comment by russHyde** [comment]
Suggest adding a unit test on `read_yaml` that expands `~` tilde to home-dir

**Comment by russHyde** [comment]
Chose to disallow the tilde, rather than expand them
