### ISSUE TITLE
'setup' should fail if a cloned packages deps arent available

### ISSUE THREAD

**Issue by russHyde** [russHyde/data_buddy#83]
When building / installing a cloned package, ensure that it's dependencies are present in the environment and fail if they are not. The pipeline currently just prints the names of missing dependencies:

```
...
Building package: ./lib/cloned_packages/miiq
✔  checking for file ‘/home/ah327h/jobs_llr/drug_markers/lib/cloned_packages/miiq/DESCRIPTION’ ...
─  preparing ‘miiq’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘miiq_0.1.0.tar.gz’
   
[1] "./lib/built_packages/miiq_0.1.0.tar.gz"
*** Installing into /home/ah327h/tools/miniconda3/envs/drug_markers/lib/R/library ***
ERROR: dependencies ‘Biobase’, ‘limma’, ‘preprocessCore’, ‘AnnotationDbi’, ‘ArrayExpress’, ‘GEOquery’, ‘RCurl’, ‘XML’ are not available for package ‘miiq’
* removing ‘/home/ah327h/tools/miniconda3/envs/drug_markers/lib/R/library/miiq’
Warning message:
In install.packages(pkg, repos = NULL, type = "source") :
  installation of package ‘./lib/built_packages/miiq_0.1.0.tar.gz’ had non-zero exit status
...
```

**Comment by russHyde** [comment]
`setup_libs.sh` does contain a `pipefail` argument.
The package-install step currently looks like:
```
function install_r_package {                                     
  PKGNAME="${1}"                                                                                                               
  PKG_LOCAL_TAR="${2}"                                                                                                         
  R_LIB_DIR="${3}"                                                                                                             
                                                                                                                               
  # Check that the given R libraries directory is valid:                                                                       
  if [[ ! -d "${R_LIB_DIR}" ]];                                                                                                
  then                                                                                                                         
    die_and_moan \                                                                                                             
    "${0}: R_LIB_DIR should be a defined directory in install_r_packages: \                                                    
    ... Current value is ${R_LIB_DIR}"                                                                                         
  fi

  if [[ ! -d "${R_LIB_DIR}/${PKGNAME}" ]] ||                                                                                   
     [[ "${R_LIB_DIR}/${PKGNAME}" -ot "${PKG_LOCAL_TAR}" ]];                                                                   
  then
    echo "*** Installing into ${R_LIB_DIR} ***" >&2
    Rscript -e "pkg = commandArgs(trailingOnly = TRUE)" \
            -e "install.packages(pkg, repos = NULL, type = 'source')" \ 
            ${PKG_LOCAL_TAR}                                  
  fi
}
...

if [[ -d "${LIB_DIR}/built_packages" ]];                                                                                       
then                                                                                                                           
  for PKG_TAR in \                                                                                                             
    $(find "${LIB_DIR}/built_packages" -name "*.tar.gz");                                                                      
  do                                                                                                                           
    # The R library directory for the current conda environment is:                                                            
    R_LIB_DIR="${CONDA_PREFIX}/lib/R/library"                                                                                  
                                                                                                                               
    # The package archives are like                                                                                            
    #   ${LIB_DIR}/built_packages/pkgname_0.1.2.333.tar.gz                                                                     
    LOCAL_PKGNAME=$(basename ${PKG_TAR} | sed -e "s/_*[0-9.]\+tar\.gz//")                                                      
                                                                                                                               
    # Install the R package if it is newer than the installed R package                                                        
    install_r_package "${LOCAL_PKGNAME}" "${PKG_TAR}" "${R_LIB_DIR}"                                                           
  done                                                                                                                         
fi
```

**Comment by russHyde** [comment]
So it looks like `Rscript -e '... install.packages(...)'` is called and fails, but is not passing an error code back to the calling process.

Furthermore:
```
# check that a failed install.packages() call returns an error code:
Rscript -e 'install.packages("lib/built_packages/miiq_0.1.0.tar.gz")'
inferring 'repos = NULL' from 'pkgs'
ERROR: dependencies ‘Biobase’, ‘limma’, ‘preprocessCore’, ‘AnnotationDbi’, ‘ArrayExpress’, ‘GEOquery’, ‘RCurl’, ‘XML’ are not available for package ‘miiq’
* removing ‘/home/ah327h/tools/miniconda3/envs/drug_markers/lib/R/library/miiq’
Warning message:
In install.packages("lib/built_packages/miiq_0.1.0.tar.gz") :
  installation of package ‘lib/built_packages/miiq_0.1.0.tar.gz’ had non-zero exit status
(drug_markers) ah327h@10:54:02:~/jobs_llr/drug_markers$ $?
0: command not found
```

**Comment by russHyde** [comment]
Suggest changing the `install_r_packages` call. 

Changing to a command-line installation step ensured that a failing install stops the setup pipeline:

```
# introducing this change into `setup_libs.sh::install_r_package`
...
  if [[ ! -d "${R_LIB_DIR}/${PKGNAME}" ]] ||                                                                                   
     [[ "${R_LIB_DIR}/${PKGNAME}" -ot "${PKG_LOCAL_TAR}" ]];                                                                   
  then                                                                                                                         
    echo "*** Installing into ${R_LIB_DIR} ***" >&2                                                                            
    R CMD INSTALL ${PKG_LOCAL_TAR}                                                                                             
  fi
...


# Means that an installation fail bubbles up to the setup pipeline when running `sidekick setup`:
(drug_markers) ah327h@11:00:41:~/jobs_llr/drug_markers$ ./sidekick setup

JOB: /home/ah327h/jobs_llr/drug_markers
./scripts/setup.sh: Running the work-package setup-script.
./scripts/setup.sh: 'buddy' has already been installed
./scripts/helpers_for_setup/setup_jupyter_r_kernel.sh: Kernel 'conda-env-drug_markers-r' is already available
make: Nothing to be done for 'all'.
*** Installing into /home/ah327h/tools/miniconda3/envs/drug_markers/lib/R/library ***
* installing to library ‘/home/ah327h/tools/miniconda3/envs/drug_markers/lib/R/library’
ERROR: dependencies ‘Biobase’, ‘limma’, ‘preprocessCore’, ‘AnnotationDbi’, ‘ArrayExpress’, ‘GEOquery’, ‘RCurl’, ‘XML’ are not available for package ‘miiq’
* removing ‘/home/ah327h/tools/miniconda3/envs/drug_markers/lib/R/library/miiq’
Traceback (most recent call last):
  File "./sidekick", line 117, in <module>
    main()
  File "./sidekick", line 111, in main
    args.func(args)
  File "./sidekick", line 29, in setup
    subprocess.run(["./scripts/setup.sh"], check=True)
  File "/home/ah327h/tools/miniconda3/envs/drug_markers/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['./scripts/setup.sh']' returned non-zero exit status 1
```

**Comment by russHyde** [comment]
fixed in https://github.com/russHyde/data_buddy/commit/f2c329321911ff90f91102eb320fba222ae3b1fd
